#!/bin/bash
# formatTexBasic -- format prodS2 for basic XeLaTeX export

cat prodLog.txt | awk 'BEGIN { FS=","}{OFS="\n" } 

$1 ~ /[Dd]ispenser/ {
printf ("%s\t%s\n%s\t%s\n%s\t%s\n%s\t%s\n\n","Description	", $1, "ItemNum", $2, "Dispenser UPC", $3, "Case UPC", $5)
} 
 
$1 ~ /[Bb]lister/ { 
printf ("%s\t%s\n%s\t%17s\n%-10s\t%10s\n%s\t%s\n%s\t%s\n\n","Description	",$1,"ItemNum",$2,"Each UPC",$3,"Sleeve UPC",$4,"Case UPC",$5)
}

$1 ~ /[Bb]undle/ { 
printf ("%s\t%s\n%s\t%17s\n%-10s\t%10s\n%s\t%s\n%s\t%s\n\n","Description	",$1,"ItemNum",$2,"Each UPC",$3,"Sleeve UPC",$4,"Case UPC",$5)
}

$1 ~ /[Cc]ard(ed)?/ { 
printf ("%s\t%s\n%s\t%17s\n%-10s\t%10s\n%s\t%s\n%s\t%s\n\n","Description	",$1,"ItemNum",$2,"Each UPC",$3,"Sleeve UPC",$4,"Case UPC",$5)
}

'
