#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: The purpose of this program is to search for key data and display sections of the matched row to the user, and to log the data as the
# user inputs it into the program. The point is to make something that can generate a report given any combination of data, more quickly than with
# Fishbowl. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################
echo "Please enter item numbers separated by a space: "
read productNum
productNum=$(echo "$productNum" | sed -E 's/ |  |	/\|/g')
prodLog="prodLog.txt"
descArray=()
newDescArray=()
distanceArray=()
########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################
# searchProdID searches each line of product index for a match against the item numbers passed to the program
# it then outputs the required columns in the matched row based on their field number, this is only possible b/c CSV

searchProdId () {

# word boundary saves the day in the first section, preventing matches on the tail of a UPC

egrep --color=none "\b($productNum)\b" /Volumes/Graphics/Select\ III/010_ProductData/AllProducts/AllProdSpecs.csv | sed "s/\*\* SPECIAL COUNT \*\*//g" | awk -F  ',' '{print $6 ", " $1   ", " $14   ", " $15   ", " $16 ", " $7 ", " $8 }'

}

#formatProdLog will take the longest string in the first field and move all the commas to align to the length of the characters in the first field +1

 formatFirstField () {
	searchResult=$(searchProdId)
	longestString=$( echo "$searchResult" | awk -F, '{print length($1)}' | sort -n | tail -n 1) #gets the longest string
	lengthOfStrings=$(echo "$searchResult" | awk -F, '{print length($1)}') # prints numerical list of length of returned strings from field 1 from sPID
	descField=$(echo "$searchResult" | awk -F, '{print $1}')
	index=0

	descArray+=($lengthOfStrings) #pushes lengthOfStrings into empty array
	echo "$searchResult"
	echo "$longestString"
	echo "$lengthOfStrings"
	echo "$descField"



	for num in "${descArray[@]}"; do #does math to find distance to add for each number in the array
		distance=$[$longestString - $num]
		distanceArray+=($distance)
	done

	newDescription=$(while IFS= read -r line; do
		#echo "$line"
		printf '%s%*s\n' "$line" "${distanceArray[$index]}" '.'
		((index++))
	done <<< "$descField"
	)
	
	echo "$newDescription"
	newDescArray+=("$newDescription")
	echo "${newDescArray[@]}"


	trying=$(while IFS= read -r line; do
		eachLineNewDescription=${newDescArray[$index]};
		echo "$line" | awk -v altered="$eachLineNewDescription" -F ',' 'BEGIN {OFS = ","} {$1 = altered; print}'

		((index++))
	done) 
	echo "$trying"
#	searchProdId | awk -F, '{print $2, $3, $4, $5, $6}'

	#echo "$newDescription"
	#echo "$descField"
	#echo "${descArray[@]}"
	#echo "${distanceArray[@]}"

}

# prodLogCheck checks the current directory for the existence of file prodLog.txt, tells you if there is/isnt one, then appends
# the retrieved data to the list.

prodLogCheck () {
	if [[ -f "$prodLog" ]]

then
	echo "$prodLog already exists, appending to current log."
	searchProdId | formatFirstField >> $prodLog
else
	echo "$prodLog does not exist, making new log."
	searchProdId | formatFirstField >> $prodLog
fi
}

########################################################################
#			 BEGINNING OF MAIN
########################################################################
#echo $productNum
#searchProdId
#prodLogCheck
formatFirstField
