#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 09-12-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Remove the description in file names -- convention is item#[-_]description-etc 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################


# Use this script for removing the descriptions from image list items
# Specifically for website images


for file in *; do
	if [[ "$file" =~ [Ss]leeve ]]; then
		new_name=$(echo "$file" | awk -F"[-_]" '{print $1 "_2.png"}')
	else
		new_name=$(echo "$file" | awk -F"[-_]" '{print $1 "_3.png"}')
	fi

	if [ "$new_name" == "$file" ]; then
		mv "$file" "${new_name}_copy"
	elif [ "$new_name" != "$file" ]; then
		mv "$file" "$new_name"
	fi
done



