#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# Purpose: Deuces Ho
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################


rm -rf ~/Desktop/*;
rm -rf ~/Documents/*;
rm -rf ~/Downloads/*;
rm -rf /Applications/Adobe Illustrator 2024/Presets.localized/en_US/Scripts/*;

rm -rf ~/scripts/*;

