#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: To crop given image set randomly within their bounds and append them into a montage image
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

# make a directory for the results
# mkdir "results-$(( $largestResults + 1 ))"



function makeLatest() {
   # this checks if there is results dir already and makes the next directory accordingly
   # if they are out of order it will make the new directory according to the highest results-xxx int
   results=$(ls -d results-* 2>/dev/null)
   if [[ -n "$results" ]]; then
      largestResults=$(ls -d results-* | sed 's/.*-//' | sort -n | tail -1)
      mkdir results-$(( $largestResults + 1 ))
   else 
      mkdir "results-1"
   fi
}

function getImageBounds() {
   dimensions=$(magick identify -format "%wx%h" "$img")
   width=$(echo $dimensions | cut -dx -f1)
   height=$(echo $dimensions | cut -dx -f2)
}

# get the image bounds of the target
bounds=""

# makeLatest
