#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Creating a template for every script made at Select Corporation. Should document the production of these tools for 
# future designers, should they be interested. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################


if [[ $# -ne 1 ]]; then
	echo "Usage: $0 inputfile"
	exit 1
fi
	echo "Please specify the field (column) to convert as a number (1 or greater)"
	read fieldNum

makeList() {	
	local file=$1
	awk -v field="$fieldNum" ' BEGIN { FS=", *" } 
	{
		printf "%s ", $field
	} END {
	print ""
	}' "$file"
}

makeList "$1" >> testing.txt
