#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Find and resize all pngs over 900k to 75% their previous size. Outputs basic before and after stats.  
# 
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################


#find ./WEB -type f -name "*.png" -exec sh -c 'identify -format "%w %h %i\n" "$1" | grep "^800" ' _ {} \;
#
# we use the find command to search for pngs greater than 900 kilobytes, then execute a shell command to call the 
# identify and convert utilities to shrink the image to 75% its previous size and output a comparison of dimensions

find . -type f -iname "*.png" -size +900k -exec sh -c 'identify "$0" && convert "$0" -resize 75% "$0" && identify "$0"' {} \; 

