#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: To format prodS2 report for illustrator so it's less messy. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

cat prodLog.txt | sed -E -e 's/^[ \t]+//g' -e 's/[ ]*$//' -e '/^[[:space:]]*$/d' | awk 'BEGIN { FS=","}{OFS="\n" }

$1 !~ /^DESCRIPTION/ {
printf ("%s\t\t\t%s\n%s\t\t\t%s\n%s\t\t\t%s\n%s\t\t\t%s\n\n","Description:", $1, "Item Number:", $2, "Each UPC:", $3, "Case UPC:", $5)
}
' | sed 's/[ ]*$//'

