#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: To format the text on the monthly flyer programs. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

cat prodLog.txt | sed -e 's/#//g' -e "s/\t//g" | awk 'BEGIN { FS=","}{OFS="\n"} 
 
$2 ~ /[1-9]/ {
gsub(/[[:space:]]/, "", $2)
printf ("%s\t%s\n%s\t%s\n%s\t\n", "Item Number: ",$2,"Description: ",$1,"Deal: " )
}
'

