#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: To do quick math, or qMath. sqMath for squares. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

#awk "BEGIN { print $1 }"

#mathString="$1"
#awk -v mathString="$1" 'BEGIN { print mathString }'

#mathString="$1"
#echo $(($mathString))


# This function takes user input and passes it to the bc command with the standard mathematics lib

function doMath {
echo "scale=5; $1" | bc -l
}

# This conditional tests the user input and ensures its a basic math expression
# It uses regex to test if the first character is one or more digits, followed 
# by 1 of 4 operators, followed by 1 or more digits

if [[ "$1" =~ ^[0-9]+[\+\-\*\/\.]+[0-9]?[0-9]+$ ]]; then
	doMath "$1"
fi

