#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: run extendScript programs from the cli. Yah buddy.  
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

scriptFolder="/Users/camdenbailey/.repos/practice_notes/006-illustrator_scripts/scripts/"
# osascript -e 'tell application "Adobe Illustrator 2023" to do javascript file "'"${scriptFolder}${1}"'"'
# fullPath="echo ${scriptFolder}${1} | sed 's/\./\\./g'"
# echo ${fullPath}
osascript -e 'tell application "Adobe Illustrator 2023" to do javascript (read file '"'${1}'"')'
# osascript -e 'tell application "Adobe Illustrator 2023" to do script (file POSIX file "'"$scriptFolder$1"'") language javascript'

