#!/bin/bash

# SCRIPT: sortByName
# AUTHOR: Camden Bailey
# DATE: 08.07.2025 
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: 
#
# set -n #Uncomment to check syntax, without execution
# remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################

target_dir="$1"
test_list=(OlympusLasColinas070517 "OakHouse 06.26.24" Testing12341234)


get_alpha_base() {
   local filename_no_ext="${1%.*}"
   echo "$filename_no_ext" | sed 's/[^a-zA-Z]//g' | tr '[:upper:]' '[:lower:]'
}


organize_folders() {
   find "$target_dir" -maxdepth 1 -type f | while read -r filepath; do
      filename=$(basename "$filepath")
      alpha_base=$(get_alpha_base "$filename")
      [[ -z "$alpha_base" ]] && continue
      mkdir -p "${target_dir}/${alpha_base}"
      mv -n "$filepath" "${target_dir}/${alpha_base}/${filename}"

      #echo "$alpha_base"
   done
}

#for item in "${test_list[@]}"; do
#   name=$(get_alpha_base $item)
#   echo $name
#done

#testing=$(get_alpha_base "${test_list[0]}")
#echo "$1"
#echo "$testing"
organize_folders


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################



