#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 2025-05-23 
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Creating a template for every script made at Select Corporation. Should document the production of these tools for 
# future designers, should they be interested. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################

#setopt EXTENDED_GLOB NO_CASE_GLOB
alphabet=$(echo {A..Z})

########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################
test_loop() {
   for char in $alphabet;
   do
      echo $char
      ls | grep -i "^$char"
   done
}

make_alpha_dirs2() {
   for char in $alphabet; do
      files=( "$char"* )
      echo $files
   done
}

make_alpha_dirs() {
   for char in "${alphabet[@]}";
   do
      files=( "$char"* )
      if [[ ${#files[@]} -eq 0 ]]; then
         echo "No files starting with '$char' - skipping"
         continue
      fi
      echo ''
      #mkdir -p "$char"
      #mv $files $char
   done
}

########################################################################
#			 BEGINNING OF MAIN
########################################################################
#test_loop
make_alpha_dirs
#make_alpha_dirs


