#!/bin/bash
#
# SCRIPT:
# AUTHOR:
# DATE:
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE:
#
# set -n #Uncomment to check syntax, without execution
# remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################
echo 'Enter the name of your new script here: '
read name;
template="/Users/camdenbailey/scripts/bashTemplate.sh"
user_name="${USER}"
creation_date=$(date "+%Y-%m-%d")

########################################################################
#		       DEFINE FUNCTIONS HERE
########################################################################
cp $template /Users/camdenbailey/scripts/$name
sed -i '' "3c\SCRIPT: ${name}\n" /Users/camdenbailey/scripts/$name
sed -i '' "4c\AUTHOR: ${user_name}\n" /Users/camdenbailey/scripts/$name
sed -i '' "5c\DATE: ${creation_date}\n" /Users/camdenbailey/scripts/$name

########################################################################
#			 BEGINNING OF MAIN
########################################################################



