#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 02-13-2025
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: finding contracts at FRC without breaking anything or otherwise causing a ruckus.  
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################



########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

# some examples for when we write the full script
# will probably want to add something that will check for new contracts that've been
# been added since the last check, and something to archive files that have been updated.
# find /Volumes/company/ -name "*.xlsx" -exec cp {} ~/Desktop/contract_db \;
#
# this specifies the search for things altered within a certain date range using mtime
# find /Volumes/company/CONTRACTS/ -name "*.xlsx" ! -path "*/OLD/*" ! -path "*/Old/*" ! -path "*/old/*" -mtime -730 -print > ./testing_find-3.txt

# find /Volumes/company/CONTRACTS/More\ Residential/ -name "*.xlsx" ! -path "*/OLD/*" ! -path "*/Old/*" ! -path "*/old/*"
