#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 2025-04-22 
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Working on scripts for searching containers quickly
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################
# examples

# find /Volumes/Graphics/Select\ III/001_Components -depth 1 -type d -name "*$1*" | sed 's/\ /\\ /g ' 
# find /given/dir -type f -iname "*testing*"
# find /given/dir -type f -iregex '.*\.ai$'

# searching server for font file extensions
# find . -type f \( -iregex '.*\.ttf$' -o -iregex '.*\.otf$' -o -iregex '.*\.woff$' -o -iregex '.*\.woff2$' -o -iregex '.*\.eot$' -o -iregex '.*\.sfd$' -o -iregex '.*\.pfb$' -o -iregex '.*\.dfont$' \) -exec cp {} ~/Desktop/000-TEST/font_search_server/ \;

# find files newer - or older + than N days. Use just number for exact times.
# find [path] -type f -mtime [+-]N

# same as above, in seconds
# find [path] -type f -mmin [+-]N

# find files accessed (read/opened) N days
# find . -type f -atime [+-]N
# find . -type f -amin [+-]N

# find files whose metadata (permissions/ownership) changed N days/minutes ago
# find . -type f -ctime [+-]N
# find . -type f -cmin [+-]N

# find files newer than reference file or timestamp
# find . -newer [reference_file]

# as above but with timestamps, worth looking into how these work
# find . -newer[acm]t "YYYY-MM-DD HH:MM:SS" 

# mixing time options for specificity
# find . -mtime -2 -atime +7
# find . -ctime 0 -mmin +60




########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

find . -type d -maxdepth 2 -iname "*$1*"


