#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: This is a quick commit script to update our github repo for notes	
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

cd /Users/selectgraphics/Desktop/002-Coding_Notes/ ;
git pull origin master;

git add . ;

echo "What is the description for this commit?"
read description

git commit -m "$description" ;
git push origin master ; 
