#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Creating a template for every script made at Select Corporation. Should document the production of these tools for 
# future designers, should they be interested. 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################

webPhoto="/Volumes/Graphics/Select III/003-Product_Images/001-allPhotos/WEB/";
regex50Counts="/\.5$/";
regexOSitems="/^OS.*/";
########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

#for each item in column 2 of prodLog
#search webPhotos for matches in the first five characters of the file name
#copy matches to current directory

# this separates items read from the prodLog into an array called givenItems. 
# it removes some unwanted characters before passing them to the array. 
# you have to do this instead of using the mapfile command that is standard on Linux machines.
# if there is more character formatting needed do it here. 

givenItems=();
while IFS= read -r line; do
	givenItems+=("$line")
done < <(awk -F, 'NR > 1 {print $2}' prodLog.txt | sed -e 's/#//g' -e 's/ //g' -e '/^[[:space:]]*$/d');

# this will go through the givenItems array and if the line matches the inverted condition below (does not match some regex)
# then it copies the matching item from the web images folder on the server. neat. 

echo "Items to find: ";
for string in "${givenItems[@]}"; do
	if ! [[ $string =~ '\.5$' ]] && ! [[ $string =~ '^OS'  ]]; then
		echo "Searching for: $string"
		find "$webPhoto" -type f -name "$string*" -exec cp -n {} . \; 
	else
		echo "$string is not for customer use."
	fi
done

# some failed experiments, worth returning to use cases later.
# justFile="$(basename "$file")";
# itemNum=${justFile:0:5};
# awk -v pattern="$itemNum" '$2 ~ pattern' prodLog.txt >> matches.txt;
# for file in webFiles, ${file:0:5}, do some awk thing that matches file against 2nd col in prodlog,
