#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: For squaring images using imagemagick, only does jpgs atm 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################


for img in *.png; do
	
# Get dimensions of the image
	dimensions=$(magick identify -format "%wx%h" "$img")
	width=$(echo $dimensions | cut -dx -f1)
	height=$(echo $dimensions | cut -dx -f2)
# Determine the longer side
	if [ $width -gt $height ]; then
		size="${width}x${width}"
	else
		size="${height}x${height}"
	fi
# Resize the canvas without changing the aspect ratio of the image
	magick convert "$img" -gravity center -background none	-extent $size "square_$img"
	#magick convert "$img" -gravity center -background grey -extent 1250x1250 "square_$img";
done

