#!/usr/bin/perl
use strict;
use warnings;

my $population = 249054112;
my $testText = "The Population of the United States is: $population ";
print "$testText\n";

#$testText =~ s/(?<=\d)(?=(\d\d\d)+\b)/,/g; #this version has both lookarounds
$testText =~ s/(\d)((\d\d\d)+\b)/$1,$2/g; #this version of the regex is without lookahead or lookbehind

print "$testText\n";
