#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 09-05-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
# Purpose: Compress PNGS -- takes stdin only, use the find command with this!
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################


########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################

while IFS= read -r file; do
	filesize=$(stat -f%z "$file")	
	filename=$(basename "$file")

	if [[ -f "$file" && $filesize -gt 700000 && $filesize -lt 2000000 ]]; then
		output_file="$(dirname "$file")/compressed-$filename"
		magick "$file" -resize 40% -define png:compression-level=9 "$output_file"
	elif [[ -f "$file" && $filesize -gt 2000000 ]]; then
		output_file="$(dirname "$file")/compressed-$filename"
                  magick "$file" -resize 15% -define png:compression-level=9 "$output_file"
	else 
		echo "$file is not compatible with this script."
	fi
done

