#!/bin/bash
# formatBlockReport -- format reports from prodS2 into a two column paragraph

cat prodLog.txt | awk 'BEGIN { FS=","}{OFS="\n" } 

$1 ~ /[Dd]ispenser/ {
printf ("%s\t\t%s\n%s\t\t\t%s\n%s\t\t%s\n%s\t\t\t%s\n\n", "Description:", $1, "Item_#", $2, "Dispenser_UPC", $3, "Case_UPC", $5)
} 
 
$1 ~ /[Bb]lister/ { 
printf ("%s\t\t%s\n%s\t\t%17s\n%-10s\t\t%10s\n%s\t\t%s\n%s\t\t\t%s\n\n","Description:",$1,"Item_#",$2,"Each_UPC",$3,"Sleeve_UPC",$4,"Case_UPC",$5)
}

$1 ~ /[Bb]undle/ { 
printf ("%s\t%s\n%s\t%17s\n%-10s\t%10s\n%s\t%s\n%s\t%s\n\n","Description:",$1,"Item_#",$2,"Each_UPC",$3,"Sleeve_UPC",$4,"Case_UPC",$5)
}

$1 ~ /[Dd]isplay/ { 
printf ("%s\t%s\n%s\t%17s\n%-10s\t%10s\n%s\t%s\n\n","Description:",$1,"Item_#",$2,"Each_UPC",$3,"Case_UPC",$5)
}
'
