#!/bin/bash

# SCRIPT: Script_Template
# AUTHOR: Camden Bailey
# DATE: 07-03-2023
# REV: 1.1.A
#
# PLATFORM: UNIX Based, zsh
#
# PURPOSE: Create the job folder for any resource requests in the graphics department. 
# It should make a folder in the proper location according to job type, client name. 
# There should be a way to select job type, current customers. Then it makes a dated folder after
# navigation. 
# 
#
# REV LIST:
#	DATE: DATE_of_REVISION
#	BY:AUTHOR_of_MODIFICATION
#	MODIFICATION: Describe what was modified
#
#
# set -n #Uncomment to check syntax, without execution
# 	 #remember to re-comment or the script won't execute
# set -x #Uncomment to debug this shell script
#
########################################################################
# 		   DEFINE FILES AND VARIABLES HERE
########################################################################

moveTo () {
cd /Volumes/Graphics/Select\ III/007_Resource-Requests/
source ~/scripts/showList

}

makeFolder () {
echo "Please enter job description:"

read job
currentDate=$(date "+%d-%m-%Y-$job")

mkdir "$currentDate"
cd "$currentDate"
}

########################################################################
#		       DEFINE FUNCTIONS HERE	
########################################################################


########################################################################
#			 BEGINNING OF MAIN
########################################################################
moveTo
source ~/scripts/showList
makeFolder

