#!/bin/bash

validAlphaNum()
{
# Validate arg: returns 0 if all upper+lower+digits; 1 otherwise
# Removes all unacceptable characters.

validchars="$(echo $1 | sed -e 's/[^- [:alnum:]]//g')" #pass output of ${...} to valid chars, echo $1 outputs arg passed
						     #to validAlphaNum() function	

if [ "$validchars" = "$1" ] ; then
	return 0 #zero means success
else 
	return 1 #1 means error for some reason
fi

}
/bin/echo -n "Enter Input: " #prompt for user input
read input		     #reads input	

# input validation, if we want to place this into another program remove the below.
if ! validAlphaNum "$input" ; then 				#if statement, ! validAlnum means if validAlnum returns 1
	echo "Please enter only letters and numbers." >&2	#runs if above condition met, >&2 means to stderr
	exit 1							#means exit script at this point
else 
	echo "Input is valid."					#if we didn't get 1 we got 0, so prompt confirmation
fi								#close that if with fi
exit 0								#causes script to end with success, 0


